
const car =[
    {
        name:"Toyota Hilux 2.8 Cd Srx 177cv 4x4",
        brand:"Toyota",
        model:"Hilux",
        year:2008,
        color:"gris",
        oil:"diesel",
        gate:4,
        kilometres:20000,
        descriptionShort:"Toyota Hilux 2.8 Cd Srx 177cv 4x4",
        descriptionLong:"MOTOR 2.8 TURBODIESEL 204CV, 4X2, 4X4 Y 4X4 REDUCIDA CON ACCIONAMIENTO ELECTRÓNICO, FAROS DELANTEROS BI-LED, FAROS TRASEROS DE LED, LUCES DIURNAS DE LED, PROTECTOR DE CÁRTER HEAVY DUTY, SISTEMA DE INGRESO INTELIGENTE, SISTEMA DE INGRESO INTELIGENTE, CONECTIVIDAD ANDROID AUTO Y APPLE CARPLAY, SISTEMA DE AUDIO PREMIUM JBL CON 8 PARLANTES Y SUBWOOFER, ECO Y POWER MODE, ETC.",
        image:"https://http2.mlstatic.com/D_NQ_NP_869695-MLA51918662241_102022-O.webp",
        price:43900,
        condition:"Usado",
        transmition:"Sincronico",
    },
    {
        name:"BMW X1 2.0 Sdrive 25i Xline 231cv",
        brand:"BMW",
        model:"X1",
        year:2017,
        color:"negro",
        oil:"Nafta",
        gate:5,
        kilometres:117000,
        descriptionShort:"BMW X1 2.0 Sdrive 25i Xline 231cv",
        descriptionLong:"Excelente estado. Todos los servicios en concesionario oficial.Versión tope de gama. Traccion integral. Motor 2 litros de 231 CV. Aceptamos permutas.",
        image:"https://http2.mlstatic.com/D_NQ_NP_862199-MLA51107673007_082022-O.webp",
        price:36300,
        condition:"Usado",
        transmition:"Automatico",
    },
    {
        name:"Chevrolet Corsa 1.4 Classic Gls",
        brand:"Chevrolet",
        model:"Corsa",
        year:2009,
        color:"verde",
        oil:"nafta",
        gate:4,
        kilometres:119000,
        descriptionShort:"Chevrolet Corsa 1.4 Classic Gls",
        descriptionLong:"Chevrolet Corsa Classic 1.4 Gls 4ptas Año 2009 - LivMotors MUY BUENAS CONDICIONES MECANICAS!!! USADOS CON GARANTIA!!!",
        image:"https://http2.mlstatic.com/D_NQ_NP_782419-MLA51920906270_102022-O.webp",
        price:1290000,
        condition:"Usado",
        transmition:"Sincronico",
    },
    {
        name:"Chevrolet Cruze II 1.4 Sedan Ltz",
        brand:"Chevrolet",
        model:"Cruze II",
        year:2017,
        color:"marron",
        oil:"Nafta",
        gate:4,
        kilometres:47000,
        descriptionShort:"Chevrolet Cruze II 1.4 Sedan Ltz",
        descriptionLong:"Chevrolet Cruze 1.4 Turbo Ltz 4p Mt Año 2017 - Liv Motors EXCELENTES CONDICIONES!!! USADOS CON GARANTIA!!!",
        image:"https://http2.mlstatic.com/D_NQ_NP_998658-MLA51919909337_102022-O.webp",
        price:3990000,
        condition:"Usado",
        transmition:"Sincronico",
    },
    {
        name:"Renault Kangoo 1.6 Furgon Ph3 Confort 5as Lc",
        brand:"Renault",
        model:"Kangoo",
        year:2014,
        color:"rojo",
        oil:"Nafta",
        gate:3,
        kilometres:100000,
        descriptionShort:"Renault Kangoo 1.6 Furgon Ph3 Confort 5as Lc",
        descriptionLong:"Renault Kangoo Confort 1.6 5plzas 2plc Año 2014 - Liv Motors MUY BUENAS CONDICIONES MECANICAS!!!USADOS CON GARANTIA!!!GRABADO DE AUTO PARTES - AL DÍA y CON DOCUMENTACIÓN LISTA PARA TRANSFERIR",
        image:"https://http2.mlstatic.com/D_NQ_NP_993659-MLA51919130354_102022-O.webp",
        price:220000,
        condition:"Usado",
        transmition:"Sincronico",
    },
    {
        name:"Citroën C4 Lounge 1.6 Thp 165 At6 Feel",
        brand:"Citroën",
        model:"C4 Lounge",
        year:2017,
        color:"blanco",
        oil:"Nafta",
        gate:4,
        kilometres:72100,
        descriptionShort:"Citroën C4 Lounge 1.6 Thp 165 At6 Feel",
        descriptionLong:"Comunicate por llamado, wspp o mensaje de esta publicación para conseguir un descuento extra!!!Asesor Alexis Castiglioni, más de 15 años en el rubro y más de 1.500 ventas, respaldan la seriedad y el respeto por el cliente. Te aseguro buena atención y excelente trato.NUESTRAS FOTOS SON REALES!!! SIN RETOQUES DIGITALES. PARA QUE VEAS LA REALIDAD.",
        image:"https://http2.mlstatic.com/D_NQ_NP_814142-MLA51919134525_102022-O.webp",
        price:3289900,
        condition:"Usado",
        transmition:"Sincronico",
    },
    {
        name:"Volkswagen Suran 1.6 I Trendline 90b",
        brand:"Volkswagen",
        model:"Suran",
        year:2010,
        color:"blanco",
        oil:"Nafta",
        gate:5,
        kilometres:99000,
        descriptionShort:"Volkswagen Suran 1.6 I Trendline 90b",
        descriptionLong:"Volkswagen Suran 1.6 Trendline Año 2010 - Liv Motors MUY BUEN ESTADO!!USADOS CON GARANTIA!!!GRABADO DE AUTO PARTES - AL DÍA y CON DOCUMENTACIÓN LISTA PARA TRANSFERIR",
        image:"https://http2.mlstatic.com/D_NQ_NP_740468-MLA51918607155_102022-O.webp",
        price:"197000",
        condition:"Usado",
        transmition:"Sincronico",
    },
    {
        name:"Peugeot 208 1.6 Gt Thp",
        brand:"Peugeot",
        model:"206",
        year:2019,
        color:"blanco",
        oil:"Nafta",
        gate:5,
        kilometres:30000,
        descriptionShort:"Peugeot 208 1.6 Gt Thp",
        descriptionLong:"PEUGEOT 208 GT MODELO 2019 30.000 KMS MOTOR 1.6 4 CILINDROS 165HP, CLIMATIZADOR AUTOMÁTICO, TECHO PANORÁMICO, TAPIZADO EN CUERO, LLANTAS DE 17 PULGADAS, AIRBAGS FRONTALES, LATERALES Y DE CORTINA, ABS, EBD, ESP, CONTROL DE VELOCIDAD CRUCERO, PANTALLA TÁCTIL DE 7 PULGADAS CON CÁMARA DE RETROCESO, APPLE CARPLAY, ANDROID AUTO, BLUETOOTH, SENSORES DE ESTACIONAMIENTO, COMPUTADORA DE ABORDO, FAROS ANTINIEBLA, LEVANTA CRISTALES Y ESPEJOS ELÉCTRICOS, SENSOR DE LLUVIA Y CREPUSCULAR, ETC.",
        image:"https://http2.mlstatic.com/D_NQ_NP_608730-MLA51918417766_102022-O.webp",
        price:17900,
        condition:"Usado",
        transmition:"Sincronico",
    },
    {
        name:"Audi A3 Sportback 2.0 T Fsi Stronic 200cv",
        brand:"Audi",
        model:"A3 Sportbaclk",
        year:2009,
        color:"negro",
        oil:"Nafta",
        gate:5,
        kilometres:126000,                   
        descriptionShort:"Audi A3 Sportback 2.0 T Fsi Stronic 200cv",
        descriptionLong:"excelente equpamiento, muy buen estado, escucho ofertas de contado, acepto permutas",
        image:"https://http2.mlstatic.com/D_NQ_NP_713760-MLA51917149913_102022-O.webp",
        price:"16000",
        condition:"Usado",
        transmition:"Automatico",
    },
    {
        name:"Jeep Renegade 1.8 Longitude At6",
        brand:"Jeep",
        model:"Renegade",
        year:2019,
        color:"negro",
        oil:"Nafta",
        gate:5,
        kilometres:37000,
        descriptionShort:"Jeep Renegade 1.8 Longitude At6",
        descriptionLong:"Jeep Renegade Longitude 1.8 At Año 2019 - Liv Motors EXCELENTES CONDICIONES!!!USADOS CON GARANTIA!!!GRABADO DE AUTO PARTES - AL DÍA y CON DOCUMENTACIÓN LISTA PARA TRANSFERIR",
        image:"https://http2.mlstatic.com/D_NQ_NP_820132-MLA51917099042_102022-O.webp",
        price:6200000,
        condition:"Usado",
        transmition:"Automatico",
    },
    ];

    module.exports = car;
