
const car = [
    {
        name: "Toyota Hilux 2.8 Cd Srx 177cv 4x4",
        brand: "Toyota",
        model: "Hilux",
        year: 2008,
        color: "gris",
        oil: "diesel",
        gate: 4,
        kilometres: 20000,
        descriptionShort: "Toyota Hilux 2.8 Cd Srx 177cv 4x4",
        descriptionLong: "MOTOR 2.8 TURBODIESEL 204CV, 4X2, 4X4 Y 4X4 REDUCIDA CON ACCIONAMIENTO ELECTRÓNICO, FAROS DELANTEROS BI-LED, FAROS TRASEROS DE LED, LUCES DIURNAS DE LED, PROTECTOR DE CÁRTER HEAVY DUTY, SISTEMA DE INGRESO INTELIGENTE, SISTEMA DE INGRESO INTELIGENTE, CONECTIVIDAD ANDROID AUTO Y APPLE CARPLAY, SISTEMA DE AUDIO PREMIUM JBL CON 8 PARLANTES Y SUBWOOFER, ECO Y POWER MODE, ETC.",
        image: "https://http2.mlstatic.com/D_NQ_NP_869695-MLA51918662241_102022-O.webp",
        price: 43900,
        condition: "Usado",
        transmition: "Sincronico",
    },
    {
        name: "BMW X1 2.0 Sdrive 25i Xline 231cv",
        brand: "BMW",
        model: "X1",
        year: 2017,
        color: "negro",
        oil: "Nafta",
        gate: 5,
        kilometres: 117000,
        descriptionShort: "BMW X1 2.0 Sdrive 25i Xline 231cv",
        descriptionLong: "Excelente estado. Todos los servicios en concesionario oficial.Versión tope de gama. Traccion integral. Motor 2 litros de 231 CV. Aceptamos permutas.",
        image: "https://http2.mlstatic.com/D_NQ_NP_862199-MLA51107673007_082022-O.webp",
        price: 36300,
        condition: "Nuevo",
        transmition: "Automatico",
    },
    {
        name: "Chevrolet Corsa 1.4 Classic Gls",
        brand: "Chevrolet",
        model: "Corsa",
        year: 2009,
        color: "verde",
        oil: "nafta",
        gate: 4,
        kilometres: 119000,
        descriptionShort: "Chevrolet Corsa 1.4 Classic Gls",
        descriptionLong: "Chevrolet Corsa Classic 1.4 Gls 4ptas Año 2009 - LivMotors MUY BUENAS CONDICIONES MECANICAS!!! USADOS CON GARANTIA!!!",
        image: "https://http2.mlstatic.com/D_NQ_NP_782419-MLA51920906270_102022-O.webp",
        price: 8203.50,
        condition: "Usado",
        transmition: "Sincronico",
    },
    {
        name: "Chevrolet Cruze II 1.4 Sedan Ltz",
        brand: "Chevrolet",
        model: "Cruze II",
        year: 2017,
        color: "marron",
        oil: "Nafta",
        gate: 4,
        kilometres: 47000,
        descriptionShort: "Chevrolet Cruze II 1.4 Sedan Ltz",
        descriptionLong: "Chevrolet Cruze 1.4 Turbo Ltz 4p Mt Año 2017 - Liv Motors EXCELENTES CONDICIONES!!! USADOS CON GARANTIA!!!",
        image: "https://http2.mlstatic.com/D_NQ_NP_998658-MLA51919909337_102022-O.webp",
        price: 25373,
        condition: "Usado",
        transmition: "Sincronico",
    },
    {
        name: "Renault Kangoo 1.6 Furgon Ph3 Confort 5as Lc",
        brand: "Renault",
        model: "Kangoo",
        year: 2014,
        color: "rojo",
        oil: "Nafta",
        gate: 3,
        kilometres: 100000,
        descriptionShort: "Renault Kangoo 1.6 Furgon Ph3 Confort 5as Lc",
        descriptionLong: "Renault Kangoo Confort 1.6 5plzas 2plc Año 2014 - Liv Motors MUY BUENAS CONDICIONES MECANICAS!!!USADOS CON GARANTIA!!!GRABADO DE AUTO PARTES - AL DÍA y CON DOCUMENTACIÓN LISTA PARA TRANSFERIR",
        image: "https://http2.mlstatic.com/D_NQ_NP_993659-MLA51919130354_102022-O.webp",
        price: 220000,
        condition: "Usado",
        transmition: "Sincronico",
    },
    {
        name: "Citroën C4 Lounge 1.6 Thp 165 At6 Feel",
        brand: "Citroën",
        model: "C4 Lounge",
        year: 2017,
        color: "blanco",
        oil: "Nafta",
        gate: 4,
        kilometres: 72100,
        descriptionShort: "Citroën C4 Lounge 1.6 Thp 165 At6 Feel",
        descriptionLong: "Comunicate por llamado, wspp o mensaje de esta publicación para conseguir un descuento extra!!!Asesor Alexis Castiglioni, más de 15 años en el rubro y más de 1.500 ventas, respaldan la seriedad y el respeto por el cliente. Te aseguro buena atención y excelente trato.NUESTRAS FOTOS SON REALES!!! SIN RETOQUES DIGITALES. PARA QUE VEAS LA REALIDAD.",
        image: "https://http2.mlstatic.com/D_NQ_NP_814142-MLA51919134525_102022-O.webp",
        price: 20921,
        condition: "Usado",
        transmition: "Sincronico",
    },
    {
        name: "Volkswagen Suran 1.6 I Trendline 90b",
        brand: "Volkswagen",
        model: "Suran",
        year: 2010,
        color: "blanco",
        oil: "Nafta",
        gate: 5,
        kilometres: 99000,
        descriptionShort: "Volkswagen Suran 1.6 I Trendline 90b",
        descriptionLong: "Volkswagen Suran 1.6 Trendline Año 2010 - Liv Motors MUY BUEN ESTADO!!USADOS CON GARANTIA!!!GRABADO DE AUTO PARTES - AL DÍA y CON DOCUMENTACIÓN LISTA PARA TRANSFERIR",
        image: "https://http2.mlstatic.com/D_NQ_NP_740468-MLA51918607155_102022-O.webp",
        price: 197000,
        condition: "Nuevo",
        transmition: "Sincronico",
    },
    {
        name: "Peugeot 208 1.6 Gt Thp",
        brand: "Peugeot",
        model: "206",
        year: 2019,
        color: "blanco",
        oil: "Nafta",
        gate: 5,
        kilometres: 30000,
        descriptionShort: "Peugeot 208 1.6 Gt Thp",
        descriptionLong: "PEUGEOT 208 GT MODELO 2019 30.000 KMS MOTOR 1.6 4 CILINDROS 165HP, CLIMATIZADOR AUTOMÁTICO, TECHO PANORÁMICO, TAPIZADO EN CUERO, LLANTAS DE 17 PULGADAS, AIRBAGS FRONTALES, LATERALES Y DE CORTINA, ABS, EBD, ESP, CONTROL DE VELOCIDAD CRUCERO, PANTALLA TÁCTIL DE 7 PULGADAS CON CÁMARA DE RETROCESO, APPLE CARPLAY, ANDROID AUTO, BLUETOOTH, SENSORES DE ESTACIONAMIENTO, COMPUTADORA DE ABORDO, FAROS ANTINIEBLA, LEVANTA CRISTALES Y ESPEJOS ELÉCTRICOS, SENSOR DE LLUVIA Y CREPUSCULAR, ETC.",
        image: "https://http2.mlstatic.com/D_NQ_NP_608730-MLA51918417766_102022-O.webp",
        price: 17900,
        condition: "Usado",
        transmition: "Sincronico",
    },
    {
        name: "Audi A3 Sportback 2.0 T Fsi Stronic 200cv",
        brand: "Audi",
        model: "A3 Sportbaclk",
        year: 2009,
        color: "negro",
        oil: "Nafta",
        gate: 5,
        kilometres: 126000,
        descriptionShort: "Audi A3 Sportback 2.0 T Fsi Stronic 200cv",
        descriptionLong: "excelente equpamiento, muy buen estado, escucho ofertas de contado, acepto permutas",
        image: "https://http2.mlstatic.com/D_NQ_NP_713760-MLA51917149913_102022-O.webp",
        price: 16000,
        condition: "Usado",
        transmition: "Automatico",
    },
    {
        name: "Jeep Renegade 1.8 Longitude At6",
        brand: "Jeep",
        model: "Renegade",
        year: 2019,
        color: "negro",
        oil: "Nafta",
        gate: 5,
        kilometres: 37000,
        descriptionShort: "Jeep Renegade 1.8 Longitude At6",
        descriptionLong: "Jeep Renegade Longitude 1.8 At Año 2019 - Liv Motors EXCELENTES CONDICIONES!!!USADOS CON GARANTIA!!!GRABADO DE AUTO PARTES - AL DÍA y CON DOCUMENTACIÓN LISTA PARA TRANSFERIR",
        image: "https://http2.mlstatic.com/D_NQ_NP_820132-MLA51917099042_102022-O.webp",
        price: 39427,
        condition: "Usado",
        transmition: "Automatico",
    },
    {
        name: "Fiat Pulse 1.3 Drive Gse Cvt",
        brand: "Fiat",
        model: "Pulse",
        year: 2022,
        color: "azul",
        oil: "Nafta",
        gate: 5,
        kilometres: 0,
        descriptionShort: "Fiat Pulse 1.3 Drive Gse Cvt",
        descriptionLong: "Concesionaria Oficial FIAT Auto Generali - NO ES PLAN DE AHORROS /**UNIDAD CON ENTREGA INMEDIATA**/ **Financiamos con la mejor TASA en CUOTAS FIJAS LA 1ra CUOTA SE PAGA A LOS 90 DÍAS* *Tomamos TU Usados como parte de Pago** ",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_848044-MLA51968640677_102022-F.webp",
        price: 26073.14,
        condition: "Nuevo",
        transmition: "Automatico",
    },

    {
        name: "Chevrolet Cruze 5 1.4 Rs At 5 p",
        brand: "Chevrolet",
        model: "Cruze 5",
        year: 2022,
        color: "rojo",
        oil: "Nafta",
        gate: 5,
        kilometres: 0,
        descriptionShort: "Chevrolet Cruze 5 1.4 Rs At 5 p",
        descriptionLong: "ANTICIPO Y CUOTAS FIJAS EN PESOS / COMPRA TU 0KM SOLO CON ENTREGA INMEDIATA!! /VENDEMOS AUTOS FISICOS CON NRO DE MOTOR Y CHASIS!!/NO ESPERES MAS POR TU 0KM!/VENTAS A TODO EL PAIS SOLO ENTREGA YA!",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_711851-MLA51967528070_102022-F.webp",
        price: 33845,
        condition: "Nuevo",
        transmition: "Automatico",
    },
    {
        name: "Toyota Hilux 2.4 Cd Dx 150cv 4x4",
        brand: "Toyota",
        model: "Hilux",
        year: 2022,
        color: "Blanco",
        oil: "Diésel",
        gate: 4,
        kilometres: 0,
        descriptionShort: "Toyota Hilux 2.4 Cd Dx 150cv 4x4",
        descriptionLong: "Hilux 4x4 DX 2.4, 0 km, sistema car play, pantalla tactil, control crucero,DISPONIBLE, ENTREGA INMEDIATA, posibilidad de facturarla. ",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_744848-MLA51964930384_102022-F.webp",
        price: 62957,
        condition: "Nuevo",
        transmition: "Sincronico",
    },
    {
        name: "Chevrolet S10 2.8 Cd 4x4 Z71",
        brand: "Chevrolet",
        model: "S10",
        year: 2022,
        color: "Gris",
        oil: "Diésel",
        gate: 4,
        kilometres: 0,
        descriptionShort: "Chevrolet S10 2.8 Cd 4x4 Z71",
        descriptionLong: "ANTICIPO Y CUOTAS FIJAS EN PESOS /COMPRA TU 0KM SOLO CON ENTREGA INMEDIATA!!/VENDEMOS AUTOS FISICOS CON NRO DE MOTOR Y CHASIS!!",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_615093-MLA51966761470_102022-F.webp",
        price: 60768.69,
        condition: "Nuevo",
        transmition: "Automatico",
    },
    {
        name: "Volkswagen Amarok 3.0 V6 Cd Highline",
        brand: "Volkswagen",
        model: "Amarok",
        year: 2022,
        color: "Blanco",
        oil: "Diésel",
        gate: 4,
        kilometres: 0,
        descriptionShort: "Volkswagen Amarok 3.0 V6 Cd Highline",
        descriptionLong: " ",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_747530-MLA51966301952_102022-F.webp",
        price: 80763.11,
        condition: "Nuevo",
        transmition: "Automatico",
    },
    {
        name: "Volkswagen Taos 1.4 250 Tsi Hero",
        brand: "Volkswagen",
        model: "Taos",
        year: 2022,
        color: "Dorado",
        oil: "Nafta",
        gate: 5,
        kilometres: 0,
        descriptionShort: "Volkswagen Taos 1.4 250 Tsi Hero",
        descriptionLong: "CONCESIONARIO OFICIAL VOLKSWAGEN ESPASA PUERTO MADERO.//VENDEDOR: EDGAR LOPEZ//11.400.000 mil pesos final patentado (CABA) puesto en la calle, incluido el flete, formularios, patentamiento y hasta el sellado, más $63.000 de obleas y verificación, NO PAGAS NADA MAS en gastos Administrativo, te queda a pagar solo el proporcional de patentes.",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_957721-MLA51965490866_102022-F.webp",
        price: 66645.46,
        condition: "Nuevo",
        transmition: "Automatico",
    },
    {
        name: "Citroën C4 Cactus 1.6 Vti 115 Feel",
        brand: "Citroën",
        model: "C4 Cactus",
        year: 2022,
        color: "Gris",
        oil: "Nafta",
        gate: 5,
        kilometres: 0,
        descriptionShort: "Citroën C4 Cactus 1.6 Vti 115 Feel",
        descriptionLong: "CAJA MANUAL Modelo 2022. Equipamiento Full. CONSULTE POR ENTREGA PACTADA: PLAN 84 CUOTAS CON 30% DE ANTICIPO",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_735322-MLA51964288499_102022-F.webp",
        price: 22800,
        condition: "Nuevo",
        transmition: "Sincronico",
    },
    {
        name: "Citroën Berlingo 1.6 Vti 115 Business",
        brand: "Citroën",
        model: "Berlingo",
        year: 2022,
        color: "Blanco",
        oil: "Nafta",
        gate: 3,
        kilometres: 0,
        descriptionShort: "Citroën Berlingo 1.6 Vti 115 Business",
        descriptionLong: "CONSULTE POR ENTREGA PACTADA: PLAN 84 Y 120 CUOTAS CON 30% DE ANTICIPO ENTREGA RAPIDA: UNIDADES AL COSTO!!! ADJUDICADAS A PEDIR LOS PRIMEROS DIAS DE NOVIEMBRE",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_865592-MLA51964402030_102022-F.webp",
        price: 24100,
        condition: "Nuevo",
        transmition: "Sincronico",
    },
    {
        name: "Renault ALASKAN 2.3 Bit 16v Intens Mt 4x4",
        brand: "Renault",
        model: "ALASKAN",
        year: 2022,
        color: "Blanco",
        oil: "Diésel",
        gate: 4,
        kilometres: 0,
        descriptionShort: "Renault ALASKAN 2.3 Bit 16v Intens Mt 4x4",
        descriptionLong: "PRECIO PUBLICADO CORRESPONDE A ANTICIPO Y 18 CUOTAS DE $97305 GASTOS INCLUIDOS CONSULTAME POR PRECIO DE CONTADO...OFERTA HASTA AGOTAR STOCK",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_736011-MLA51967751846_102022-F.webp",
        price: 57300,
        condition: "Nuevo",
        transmition: "Sincronico",
    },
    {
        name: "Renault Kangoo Ii Express Confort 5a 1.6 Sce",
        brand: "Renault",
        model: "Kangoo",
        year: 2022,
        color: "Gris",
        oil: "Nafta",
        gate: 3,
        kilometres: 0,
        descriptionShort: "Renault Kangoo Ii Express Confort 5a 1.6 Sce",
        descriptionLong: "Horario de atención: Lunes a Sábados de 9:00hs a 19:00hs Atendemos tu consulta vía ON LINE por WhatsApp, por llamada o videollamada. ASESORA COMERCIAL: THIAGO ACOSTA LEPIC sucursal: BOEDO Dirección: Av. La Plata 1588, BOEDO, CABA",
        image: "https://http2.mlstatic.com/D_NQ_NP_2X_911483-MLA51963762972_102022-F.webp",
        price: 29675,
        condition: "Nuevo",
        transmition: "Sincronico",
    },
];

module.exports = car;
